### ISSUE TITLE
Can Flixtor recognise more movie formats?

### ISSUE THREAD

**Issue by ghost** [TorrentLookup/Flixtor#49]
I was wondering if there is some posibility for Flixtor app to recognice more Movie formats/codecs? That way you get less switches into VLC player and you get also some sorth of solution for subs to be available at ''all time''.. 
VLC switch should be reserved for some rear formats/codec.. It's just an idea anyway, (well, it's more like question for witch i realy like know the answer..) :)

**Comment by Japoilski** [comment]
Subtitles for VLC #48

I will add a button where you can switch between vlc or the default player at all time.

Also, on this picture you can see which format will be played on VLC instead of the default player.

![image](https://cloud.githubusercontent.com/assets/7190299/2811731/89f88a6c-ce2d-11e3-8a4e-db2ddc9058f2.png)

**Comment by ghost** [comment]
This is great . i see you work already on solution for these stuff..
